# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/forms/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 450)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_field = QtWidgets.QPlainTextEdit(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.message_field.setFont(font)
        self.message_field.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.message_field.setObjectName("message_field")
        self.verticalLayout.addWidget(self.message_field)
        self.send_button = QtWidgets.QPushButton(self.central_widget)
        self.send_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.send_button.setObjectName("send_button")
        self.verticalLayout.addWidget(self.send_button)
        self.log_field = QtWidgets.QPlainTextEdit(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.log_field.setFont(font)
        self.log_field.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.log_field.setUndoRedoEnabled(False)
        self.log_field.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.log_field.setReadOnly(True)
        self.log_field.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.log_field.setObjectName("log_field")
        self.verticalLayout.addWidget(self.log_field)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "App"))
        self.send_button.setToolTip(_translate("MainWindow", "Send message to VRChat Chatbox"))
        self.send_button.setText(_translate("MainWindow", "Send"))
