# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/forms/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 428)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.message_field = QtWidgets.QPlainTextEdit(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.message_field.setFont(font)
        self.message_field.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.message_field.setObjectName("message_field")
        self.horizontalLayout_7.addWidget(self.message_field)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.language_selector = QtWidgets.QComboBox(self.central_widget)
        self.language_selector.setObjectName("language_selector")
        self.language_selector.addItem("")
        self.language_selector.setItemText(0, "")
        self.language_selector.addItem("")
        self.language_selector.addItem("")
        self.language_selector.addItem("")
        self.verticalLayout.addWidget(self.language_selector)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.send_button = QtWidgets.QPushButton(self.central_widget)
        self.send_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.send_button.setObjectName("send_button")
        self.verticalLayout_2.addWidget(self.send_button)
        self.log_field = QtWidgets.QPlainTextEdit(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.log_field.setFont(font)
        self.log_field.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.log_field.setUndoRedoEnabled(False)
        self.log_field.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.log_field.setReadOnly(True)
        self.log_field.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.log_field.setObjectName("log_field")
        self.verticalLayout_2.addWidget(self.log_field)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "App"))
        self.language_selector.setItemText(1, _translate("MainWindow", "日本語"))
        self.language_selector.setItemText(2, _translate("MainWindow", "中文"))
        self.language_selector.setItemText(3, _translate("MainWindow", "한국어"))
        self.send_button.setToolTip(_translate("MainWindow", "Send message to VRChat Chatbox"))
        self.send_button.setText(_translate("MainWindow", "Send"))
